widgetsExample:
<widgetsExample>:

    #rows:3
    cols:3
    Button:
        text:'+'

        on_press:root.plus()
    Label:
        font_name:'fonts/Lcd.ttf'
        text:root.my_text
        font_size:'80dp'
        color:1,.5,1,1
    Button:
        text:'-'
        bold:True
        font_size:10

        on_press:root.minus()
    ToggleButton:
        text:'Toggle'
        on_state:root.on_state(self)
